### ISSUE TITLE
Running on GPU

### ISSUE THREAD

**Issue by mzdaneshmand** [Alpaca-zip/ultralytics_ros#33]
Is it possible to make the model run on GPU instead of CPU?

**Comment by Alpaca-zip** [comment]
Thank you @mzdaneshmand  for your valuable report.

You can specify cuda device=0/1/2/3 instead of cpu in the track/predict function. Please refer to the following example.

```py
results = self.model.track(
    source=numpy_image,
    conf=self.conf_thres,
    iou=self.iou_thres,
    max_det=self.max_det,
    classes=self.classes,
    tracker=self.tracker,
    verbose=False,
    device=0, # cuda device number
)
```

Reference : https://docs.ultralytics.com/modes/predict/#inference-arguments:~:text=device%20to%20run%20on%2C%20i.e.%20cuda%20device%3D0/1/2/3%20or%20device%3Dcpu

Best regards,

**Comment by Alpaca-zip** [comment]
The content of this issue in `noetic-devel` has been improved with https://github.com/Alpaca-zip/ultralytics_ros/pull/35.

If you want to specify the device to be used by yolo (e.g. cpu or cuda:0), modify the launch file as follows.
```xml
<arg name="device" default="cpu"/> <!-- cpu -->
```
```xml
<arg name="device" default="0"/> <!-- cuda:0 -->
```

Thank you all for your support to the project.
___
**Tasks**
- [x] melodic-devel
- [x] noetic-devel
- [x] humble-devel
